[project]
name = "redib"
version = "0.1.0"
description = "TUI Redis browser"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual>=0.87.1",
]

[dependency-groups]
dev = [
    "textual-dev>=1.7.0",
]
